<?php

/*
|--------------------------------------------------------------------------
| Crawlers config
|--------------------------------------------------------------------------
*/
$config['crawlers'] = array (
    "bots" =>  array (
        "blocked" => array (
            "aboundexbot",
            "adidxbot",
            "adsacomponent",
            "ahrefsbot",
            "aqua_products",
            "archive.org_bot",
            "asterias",
            "b2w",
            "backlinkcrawler",
            "baidu",
            "bing",
            "bingbot",
            "blekkobot",
            "blexbot",
            "blo.gs",
            "blowfish",
            "bot",
            "bullseye",
            "bunnyslippers",
            "cherry pick",
            "collect",
            "copernic",
            "copyrightcheck",
            "cosmos",
            "crawl",
            "crawlx",
            "crescent",
            "cuil",
            "docomo",
            "domainsdb.net",
            "dotbot",
            "dsearch",
            "emailwolf",
            "exabot",
            "extractorpro",
            "ezooms",
            "fairad client",
            "feedfetcher",
            "feedfetcher-google",
            "freefind",
            "getright",
            "gigabot",
            "google",
            "googlebot",
            "grub",
            "harvest",
            "hatena antenna",
            "hloader",
            "httplib",
            "humanlinks",
            "ia_archiver",
            "icarus6j",
            "iron33",
            "jakarta",
            "jamesbot",
            "java",
            "keyword density",
            "larbin",
            "libweb",
            "linkdexbot",
            "linkextractorpro",
            "linkwalker",
            "lipperhey spider",
            "lwp-trivial",
            "majestic",
            "majestic-12",
            "majestic-seo",
            "mata hari",
            "meanpathbot",
            "miixpc",
            "mister pix",
            "mj12bot",
            "moget",
            "ms",
            "msnbot",
            "msnptc",
            "naver",
            "ncbot",
            "nerdybot",
            "netants",
            "netmechanic",
            "newsblur",
            "nicerspro",
            "nutch",
            "nutch",
            "offline explorer",
            "ole control",
            "openfind data gathere",
            "openfind",
            "pagesinventory",
            "perman",
            "pro",
            "prowebwalker",
            "pycurl",
            "python-urllib",
            "queryn metasearch",
            "radiation retriever",
            "repomonkey",
            "rma",
            "rogerbot",
            "scan",
            "scoutjet",
            "search",
            "searchmetricsbot",
            "semalt",
            "semalt.com",
            "semrushbot",
            "seokicks-robot",
            "serpstat",
            "siphon",
            "sistrix",
            "sitebot",
            "sitesnagger",
            "sogou",
            "sootle",
            "soso",
            "spanner",
            "spbot",
            "spider",
            "spiderman",
            "spyder",
            "spyfu",
            "stanford",
            "suzuran",
            "szukacz",
            "teleport",
            "teleportpro",
            "telesoft",
            "the intraformant",
            "thenomad",
            "tineye",
            "tocrawl",
            "turingos",
            "twitterbot",
            "url control",
            "url_spider_pro",
            "urly warning",
            "vci",
            "vespa",
            "web image collector",
            "webauto",
            "webbandit",
            "webcopier",
            "webenhancer",
            "webmeup",
            "webmeup.com",
            "websauger",
            "website quester",
            "webster",
            "webstripper",
            "webvac",
            "webzip",
            "wget",
            "whowhere",
            "www-collector-e",
            "xenu",
            "xovibot",
            "y!j",
            "yahoo",
            "yandex",
            "zeus",
            ),
      ),
);
